### ISSUE TITLE
Add more info about pwsafe project for Flathub repository

### ISSUE THREAD

**Issue by igor2x** [flathub/org.pwsafe.pwsafe#1]
Just a reminder issue, not to forget to add additional information for Password Safe project in Flathub.org.

If you agree and when ready then please add additional info in file: https://github.com/pwsafe/pwsafe/blob/master/install/metainfo/org.pwsafe.pwsafe.metainfo.xml like described in thread: https://github.com/flathub/flathub/pull/4890#issuecomment-1919485406

Probably there is no rush to publish new flatpak version, just to update Flathub.org info. I suggest you commit changes to XML file like today and when new flatpak version is pushed like in few weeks/months to Flathub.org this new info will be automatically available.

**Comment by ronys** [comment]
Done in commit 56cc7e27b11d81988406e5c07ea599f7093fd081 in the https://github.com/pwsafe/pwsafe repo

**Comment by igor2x** [comment]
Now I see when flatpak is created it is probably better place to report flapak related bugs on this flathub/org.pwsafe.pwsafe bug tracker.

I suggest to change "bugtracker" from https://github.com/pwsafe/pwsafe/issues
to https://github.com/flathub/org.pwsafe.pwsafe/issues in file:
https://github.com/pwsafe/pwsafe/blob/master/install/metainfo/org.pwsafe.pwsafe.metainfo.xml

Like I see it is common in Flathub.org web page that issues are reported to flatpak bug tracker and not on upstream bug tracker.

**Comment by ronys** [comment]
I'm not sure I agree. The metainfo file is part of the pwsafe repo, and there's nothing flathub or flatpak specific there.
Let's keep it as is for now. If we get flatpak-specific bugs, we can always change this later.
