### ISSUE TITLE
Yubikey not supported in flatpak Password Safe v1.18.2

### ISSUE THREAD

**Issue by igor2x** [flathub/org.pwsafe.pwsafe#4]
Installed Password Safe 1.18.2 as flatpak from Flathub on Ubuntu 23.10.
From menu Manage there is no "YubiKey" entry like it is on deb package.

**Comment by ronys** [comment]
Odd. That looks like NO_YUBI was defined (by setting -DNO_YUBI=ON) ??

**Comment by igor2x** [comment]
In manifest file the only current options are:

```
config-opts:
  - -DNO_GTEST=ON
  - -DGTEST_BUILD=OFF
```

Both of them are options to not perform tests, because I have had no idea how to include all of this tests in build system and I imagined if tests are run using deb/rpm, there is probably no need to rerun them using flatpak.

But you see there is no  `-DNO_YUBI=ON` option.

**Comment by nobugshere** [comment]
Yubikey now works, as of 1.19.1.  PR #9
